#WORKING, successfully did for 19 and 21
---
- hosts: all
  tasks:
    - name: Ensure python3-venv is installed (Required for Ubuntu/Debian systems)
      ansible.builtin.apt:
        name: python3-venv
        state: present
        update_cache: yes
      become: yes  # This tells Ansible to use sudo for this specific step

    - name: Install tracking dependencies into a safe virtual environment
      ansible.builtin.pip:
        name:
          - "opencv-contrib-python>=4.8.0"
          - pyrealsense2
          - python-osc
        virtualenv: ~/tracking_venv
        virtualenv_command: python3 -m venv


#COMMAND WORKS FOR ALL 4 MACHINES
#ansible-playbook -i config/bees.ini setup/ping.yml -k -K





#Need this if SSH key changes, but above command should suffice
# env ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i config/bees.ini setup/ping.yml -k -K

        #ANSIBLE_HOST_KEY_CHECKING=False prevents Ansible from blocking connections if a Beelink's SSH identity
  ##prompt for the sudo password, which is required for the installation tasks to succeed.